GET http://localhost:3000/cargoRouter/
Content-Type: application/json

###

POST http://localhost:3000/cargoRouter/
Content-Type: application/json

{
    "id": 10,
    "nombre": "Preceptora",
    "tipo": "apoyo"
}

