### GET todas las personas
GET http://localhost:3000/personRouter
Content-Type: application/json

### GET una persona por ID
GET http://localhost:3000/personRouter/cf4f1686-2a96-4730-8fae-6be3e524420f
Content-Type: application/json

### POST crear una nueva persona
POST http://localhost:3000/personRouter/
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "dni": "123456790",
  "email": "juan.perez@example.com",
  "celular": "123456789",
  "fecha_nac": "1990-01-01",
  "direccion": "Calle Falsa 123",
  "legajo": "LEG123",
  "cargo_id": "20"
}

### GET personas por nombre
GET http://localhost:3000/personas/nombre/Juan
Content-Type: application/json

### GET personas por apellido
GET http://localhost:3000/personas/apellido/Pérez
Content-Type: application/json

### GET personas por edad
GET http://localhost:3000/personas/edad/30
Content-Type: application/json

### GET personas por fecha de nacimiento
GET http://localhost:3000/personas/fecha-nacimiento/1990-01-01
Content-Type: application/json

### GET personas por DNI
GET http://localhost:3000/personas/dni/12345678
Content-Type: application/json

### GET personas por email
GET http://localhost:3000/personas/email/juan.perez@example.com
Content-Type: application/json